name: Pipeline de CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: pipeline

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ secrets.NODE_VERSION }}" 

      - name: Instalar dependências
        run: npm install

      - name: Configurar variáveis de ambiente
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/testdb" >> $GITHUB_ENV

      - name: Rodar migrações do Prisma
        run: npx prisma migrate deploy --schema=./src/prisma/schema.prisma

      - name: Gerar Prisma Client
        run: npx prisma generate --schema=./src/prisma/schema.prisma

      - name: Verificar Prisma Client
        run: test -d node_modules/.prisma/client

      - name: Construir projeto
        run: npm run build

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ secrets.NODE_VERSION }}" 

      - name: Instalar dependências
        run: npm install

      - name: Executar linter
        run: npm run lint

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ secrets.NODE_VERSION }}" 

      - name: Instalar dependências
        run: npm install

      - name: Executar formatter
        run: npm run format
