name: Pipeline de CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" 

      - name: Instalar dependências
        run: npm install

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Verificar Prisma Client
        run: test -d node_modules/.prisma/client

      - name: Construir projeto
        run: npm run build

      - name: Executar testes
        run: npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Atualizado para a versão 18

      - name: Instalar dependências
        run: npm install

      - name: Executar linter
        run: npm run lint

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Atualizado para a versão 18

      - name: Instalar dependências
        run: npm install

      - name: Executar formatter
        run: npm run format

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Fazer deploy para produção
        run: ./deploy.sh # Substitua pelo seu script de deploy

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Atualizado para a versão 18

      - name: Instalar dependências
        run: npm install

      - name: Executar verificação de segurança
        run: npm audit
